version: '3'
services:
  web:
    image: mostafatahboub/my-static-website:latest
    ports:
      - "80:80"
    environment:
      - NGINX_ENV=production
    networks:
      - production_network

networks:
  production_network:
    driver: bridge
